### ISSUE TITLE
Before I fork this

### ISSUE THREAD

**Issue by aadamsx** [zhenyasav/progress#2]
Any chance the package without coffeescript and less?  I'll have to add the extra code for these libraries in order to use zhenya:progress only -- which is kinda much.

**Comment by zhenyasav** [comment]
Meteor will compile coffee and less files into minified js and css before shipping them to the client, so no extra code from coffee or less will impact your client load time. I don't have time to do this for you, but it's very straight forward to convert coffee into js with `coffee -c coffeefile.coffee` and `lessc lessfile.less` on your own fork.

**Comment by aadamsx** [comment]
I've already done this and it's up on atmosphere.  I'll have to post the code to github when I get a chance.
